[tool.isort]
profile = "black"
src_paths = "src/api"

[tool.pytest.ini_options]
pythonpath = "src/api"
addopts = "--verbose --cov src"
testpaths = "tests"

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

[tool.mypy]
mypy_path = "src/api"
explicit_package_bases = true
strict = true
